# Generated by Django 6.0.4 on 2026-05-07 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_alter_post_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=255)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='card/avatar/')),
                ('price', models.PositiveIntegerField()),
                ('duration_days', models.PositiveIntegerField(default=2)),
                ('type', models.CharField(choices=[('pin_post', 'pin_post'), ('premium', 'premium')], default='premium', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Card plan',
                'verbose_name_plural': 'Cards plans',
                'db_table': 'Card',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='InventoryCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], max_length=10)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_card', to='store.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventary', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'InventoryCard',
                'verbose_name_plural': 'InventoryCards',
                'db_table': 'InventoryCard',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mana_amount', models.IntegerField(help_text='Кол-во маны (отрицательное при трате, положительное при получении)')),
                ('status', models.CharField(choices=[('buy_card', 'Покупка карточки'), ('end_card', 'Закончился срок карточки'), ('mana_accrual', 'Начисление маны'), ('mana_spend', 'Трата маны')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='store.inventorycard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'История инвентаря',
                'verbose_name_plural': 'История инвентаря',
                'db_table': 'inventory_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PinnedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penned_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pin_info', to='main.post')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_post', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PinnedPost',
                'verbose_name_plural': 'PinnedPosts',
                'db_table': 'PinnedPost',
            },
        ),
        migrations.AddIndex(
            model_name='inventorycard',
            index=models.Index(fields=['user', 'status'], name='InventoryCa_user_id_68e897_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorycard',
            index=models.Index(fields=['end_date', 'status'], name='InventoryCa_end_dat_fc64cb_idx'),
        ),
    ]
