# Generated by Django 6.0.4 on 2026-05-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pinnedpost',
            old_name='penned_at',
            new_name='pinned_at',
        ),
        migrations.AlterField(
            model_name='inventoryhistory',
            name='status',
            field=models.CharField(choices=[('buy_card', 'Покупка карточки'), ('end_card', 'Закончился срок карточки'), ('mana_accrual', 'Начисление маны'), ('mana_spend', 'Трата маны'), ('mana_send', 'Передача маны')], max_length=20),
        ),
    ]
