# Generated by Django 6.0.4 on 2026-05-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_penned_at_pinnedpost_pinned_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryhistory',
            name='mana_amount',
            field=models.IntegerField(blank=True, help_text='Кол-во маны (отрицательное при трате, положительное при получении)', null=True),
        ),
    ]
